### ISSUE TITLE
[Bug]: User Activity Recognition not working

### ISSUE THREAD

**Issue by ravsahumcn** [android/platform-samples#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

Location

### In a specific sample?

useractivityrecog

### What happened?

I tried to run the Activity Recognition Sample code on the One Plus mobile and also cloned the repo and found that it's not working. I am unable to get any update.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ravsahumcn** [comment]
no response received yet.

**Comment by christxph** [comment]
Same problem on a OnePlus 7 (GM1903)
