### ISSUE TITLE
[Bug]: Geofence events are not triggered

### ISSUE THREAD

**Issue by bDev10** [android/platform-samples#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

Location

### In a specific sample?

GeofencingScreen.kt

### What happened?

Geofencing events are not received unless you open Google Maps.

**Example steps to reproduce:**
1. Run currently newest emulator with API 33.
2. Open "Platform Samples" sample app.
3. Go to "Location - Create and monitor Geofence" screen and grant all required permissions (location and location in background permissions are required if not granted earlier).
4. Check "Statue of Liberty".
5. Set current location in emulator settings far from the Statue of Liberty (more than 100 meters away).
6. Change current location in emulator settings to the coordinates of Statue of Liberty.
7. **Geofence alert not triggered (no "Geofence Alert : ..." message shown in UI nor in logs).**
8. Open "Maps" app.
9. Switch back to "Platform Samples" app.
10. Now geofence alert was triggered ("Geofence Alert : ..." message is shown in UI and logs).

**Expected behavior:**
In point 7 above, the geofence alert should be triggered (without the need to open "Maps" app).

This behavior is observed also on other OS versions. I decided to check samples because it stopped working in my app at some point, probably after some system security update, since earlier it worked properly on the same app version.

This is critical issue, since it affects a lot of apps in the production and users are reporting that geofencing related features stopped working.

_Side note: might be same or similar bug as described in case 2 of [this issue](https://github.com/android/platform-samples/issues/123) however the mentioned issue covers few other potentially unrelated cases and lacks the detailed steps to reproduce this particular case, so opening this for clarity._

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by georkost4** [comment]
@bDev10 Hey, noticed that as well do you experience this on physical devices as well or is this limited to emulators?
