### ISSUE TITLE
[Bug]: Minor spelling Rational should be Rationale

### ISSUE THREAD

**Issue by rcrosbie-avaya** [android/platform-samples#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

General

### In a specific sample?

TelecomCallScreen.kt

### What happened?

In the code for CallControls:
`var showRational`
should be
`var showRationale`

Likewise
`private fun RationalMicDialog`
should be
`private fun RationaleMicDialog`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yrezgui** [comment]
#134 and #135 fix this issue
