### ISSUE TITLE
Do you have a non composite version[FR]: 

### ISSUE THREAD

**Issue by jack9095** [android/platform-samples#137]
### Is there an existing FR for this?

- [X] I have searched the existing issues

### For which area is this FR?

General

### Describe the feature request

Do you have a non composite version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yrezgui** [comment]
Hi @jack9095, did you mean non-Compose (using Android Views)? Several samples are written both in Compose and in Android Views. Is there a particular one you would like to see written in Android Views?
