### ISSUE TITLE
[Bug]: Bluetooth Low Energy (BLE) samples GATT page not found

### ISSUE THREAD

**Issue by albertyckwok** [android/platform-samples#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

General

### In a specific sample?

GATTServerSample.kt

### What happened?

Hi, the "Create a GATT server, advertise and handle connections" on Bluetooth Low Energy (BLE) samples reutnr page not found. The following is what I get:
```
404 - page not found
The

main
 branch of

platform-samples
 does not contain the path

samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/GATTServerSample.kt.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yrezgui** [comment]
Fixed by @lukehopkinsdev in #140
