### ISSUE TITLE
[Bug]: Build fails on Windows because of wrong file separators

### ISSUE THREAD

**Issue by DeweyReed** [android/platform-samples#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

General

### What happened?

The build fails because samples are missing, and Hilt cannot inject.

My solution is to replace `/` in [settings.build.kts](https://github.com/android/platform-samples/blob/54e8d71610a7d85aabb8d28495647375669661a2/settings.gradle.kts#L38) with `File.separator`. And then everything works as expected. I don't know if it's the correct solution. If so, I'm also happy to open a PR.

### Relevant logcat output

```shell
platform-samples\app\build\generated\hilt\component_sources\debug\com\example\platform\app\MainApp_HiltComponents.java:133: error: [Dagger/MissingBinding] java.util.Set<com.google.android.catalog.framework.base.CatalogSample> cannot be provided without an @Provides-annotated method.
  public abstract static class SingletonC implements MainApp_GeneratedInjector,
                         ^
      java.util.Set<com.google.android.catalog.framework.base.CatalogSample> is injected at
          com.google.android.catalog.framework.ui.CatalogActivity.catalogSamples
      com.example.platform.app.MainActivity is injected at
          com.example.platform.app.MainActivity_GeneratedInjector.injectMainActivity(com.example.platform.app.MainActivity) [com.example.platform.app.MainApp_HiltComponents.SingletonC �� com.example.platform.app.MainApp_HiltComponents.ActivityRetainedC �� com.example.platform.app.MainApp_HiltComponents.ActivityC]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcelpinto** [comment]
Thanks for reporting. This indeed shouldn't be hardcoded and use the File.separator value instead.

Here is the PR #20 

Could you verify it works for Windows?

**Comment by DeweyReed** [comment]
It works like a charm now! :D
