### ISSUE TITLE
[Bug]: Update windows sample to stable 1.1.0

### ISSUE THREAD

**Issue by marcelpinto** [android/platform-samples#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

User Interface

### In a specific sample?

WindowDemosActivity.kt

### What happened?

Androidx Window 1.1.0 introduces many breaking changes. The sample should be updated to reflect the latest ones

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by romanofranz** [comment]
Fixed with https://github.com/android/platform-samples/pull/41
