### ISSUE TITLE
[Bug]: Platform-samples won't find the java toolchain

### ISSUE THREAD

**Issue by FerdinandoPH** [android/platform-samples#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

General

### What happened?

I have followed the instructions for running the platform-samples project, but Android Studio says that there is no vaild java toolchain. I have tried everything I could think of, but to no avail (foojay resolver appears won't work because it is "duplicated" somewhere in the code). Where can I find said toolchain and where should I place it for gradle to find it. I have a windows 11 pc

### Relevant logcat output

```shell
A problem occurred configuring root project 'Platform Samples'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':classpath'.
      > Failed to calculate the value of task ':build-logic:compileJava' property 'javaCompiler'.
         > No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.
            > No locally installed toolchains match (see https://docs.gradle.org/8.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1/userguide/toolchains.html#sub:download_repositories).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FerdinandoPH** [comment]
Installing jdk 17.0.8 yields this error:

`A problem occurred configuring root project 'Platform Samples'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not resolve project :build-logic.
        Required by:
            project :
         > No matching variant of project :build-logic was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1' but:
             - Variant 'apiElements' capability com.example.platform.plugin.buildlogic:build-logic:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
             - Variant 'mainSourceElements' capability com.example.platform.plugin.buildlogic:build-logic:unspecified declares a component, and its dependencies declared externally:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
                     - Doesn't say anything about its usage (required runtime)
             - Variant 'runtimeElements' capability com.example.platform.plugin.buildlogic:build-logic:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
             - Variant 'testResultsElementsForTest' capability com.example.platform.plugin.buildlogic:build-logic:unspecified:
                 - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                     - Doesn't say anything about its target Java version (required compatibility with Java 11)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.1')
                     - Doesn't say anything about its usage (required runtime)`

**Comment by marcelpinto** [comment]
Which Android Studio version are you using? The #54 should have fixed this

**Comment by FerdinandoPH** [comment]
> Which Android Studio version are you using? The #54 should have fixed this

I'm using the latest version from the website (2022.3.1)
