### ISSUE TITLE
[Bug]: Task 'wrapper' not found in project ':samples:user-interface:appwidgets'.

### ISSUE THREAD

**Issue by davehorner** [android/platform-samples#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

User Interface

### In a specific sample?

AppWidget which is now AppWidgets

### What happened?

The code in user-interface still builds fine.  The latest in platform-samples does not build and gives the error
```
Task 'wrapper' not found in project ':samples:user-interface:appwidgets'.
```

I see no wrapper, but this is using build.gradle.kts.
Android Studio Flamingo | 2022.2.1 Patch 1

### Relevant logcat output

```shell
Task 'wrapper' not found in project ':samples:user-interface:appwidgets'.

* Try:
> Run gradle tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcelpinto** [comment]
How are you trying to build this? Could you provide the command?

btw, if you want to run the AppWidget sample just run the full project and open the appwidget or use the "App Widgets" run configuration in Android Studio to open directly the sample

**Comment by davehorner** [comment]
I've got a clone of the repo and I'm opening via Open.. opening android\platform-samples\samples\user-interface\appwidgets.

**Comment by davehorner** [comment]
I tried adding
```
+    tasks.withType<Wrapper> {
+        distributionUrl = "https://services.gradle.org/distributions/gradle-7.4-bin.zip"
+    }
+
```
it did not help.

**Comment by marcelpinto** [comment]
I see the issue. You must open the full project. This is a single project that contains sample-modules. You are trying to open a standalone module, that won't work.

See instructions: https://github.com/android/platform-samples#how-to-run

**Comment by davehorner** [comment]
Clone the repository
Open the whole project in Android Studio.
Sync & Run app configuration

None of that specifies which project is the whole project.

**Comment by marcelpinto** [comment]
The cloned repository is the full project. Just open the folder platform-samples in Android Studio

**Comment by davehorner** [comment]
https://stackoverflow.com/questions/72382146/the-project-is-using-an-incompatible-version-agp-7-3-0-alpha07-of-the-android everyone pointed to upgrade.
I installed Android Studio Giraffe | 2022.3.1 Patch 1 and everything is working.  I'm debugging in a UI everything built.  Have a great day.

**Comment by davehorner** [comment]
https://github.com/android/platform-samples/commit/c5cd35e3afcee6435f55db7535e58cee87655ce7

it would really be nice to lose the old code references too.
