### ISSUE TITLE
[Bug]: bglocationaccess will only run every 15 minutes, not every 2 minutes as stated

### ISSUE THREAD

**Issue by swilson** [android/platform-samples#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

Location

### In a specific sample?

BgLocationAccessScreen.kt

### What happened?

The example claims it checks for background location every 2 minutes, however it uses PeriodicWorkRequestBuilder, whose minimum interval is MIN_PERIODIC_INTERVAL_MILLIS, which is 15 minutes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcelpinto** [comment]
That's correct thanks for noticing. I send updated it to 15min
